name: build-mono-exe

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: find csproj
        id: findproj
        run: |
          proj=$(ls *.csproj | head -n 1)
          echo "PROJECT=$proj" >> $GITHUB_OUTPUT

      - name: publish project (mono-compatible)
        run: dotnet publish ${{ steps.findproj.outputs.PROJECT }} /p:UseAppHost=false /p:SelfContained=false

      - name: show exe location
        run: find . -name "*.exe"

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonsecdeobfuscator
          path: '**/publish/*.exe'
